/**
 * User API
 * OpenAPI Specification for the Apigee user api service endpoint.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model


case class Add (
  num1: Option[Number] = None,
  num2: Option[Number] = None
)

