---
swagger: "2.0"
info:
  description: "OpenAPI Specification for the Apigee user api service endpoint."
  version: "1.0.0"
  title: "User API"
host: "3.237.197.88:9000"
basePath: "/api/user"
schemes:
- "http"
paths:
  /create:
    post:
      summary: "Create an account"
      operationId: "createPOST"
      parameters:
      - in: "body"
        name: "body"
        description: "request payload in application/json"
        required: true
        schema:
          $ref: "#/definitions/sign-up"
      responses:
        "200":
          description: "{\"status\":\"success\",\"data\":{\"isSignupSuccess\":\"true\"\
            },\"error\":\"\"}"
      x-swagger-router-controller: "Default"
  /login:
    post:
      summary: "Login to account"
      operationId: "loginPOST"
      parameters:
      - in: "body"
        name: "body"
        description: "Request payload in application/json"
        required: true
        schema:
          $ref: "#/definitions/login"
      responses:
        "200":
          description: "{\"status\":\"success\",\"data\":{\"isLoginSuccess\":\"true\"\
            ,\"token\":\"....\"},\"error\":\"\"}"
      x-swagger-router-controller: "Default"
  /emailexist:
    get:
      summary: "Check email already exists or not"
      operationId: "emailexistGET"
      parameters:
      - name: "email"
        in: "query"
        description: "User email"
        required: true
        type: "string"
      responses:
        "200":
          description: "{\"status\":\"success\",\"data\":{\"isEmailExists\":\"true\"\
            },\"error\":\"\"}"
      x-swagger-router-controller: "Default"
  /sum:
    post:
      summary: "Sum of two numbers"
      operationId: "sumPOST"
      parameters:
      - in: "body"
        name: "body"
        description: "Request payload in application/json"
        required: true
        schema:
          $ref: "#/definitions/add"
      - name: "Authorization"
        in: "header"
        required: true
        type: "string"
      responses:
        "200":
          description: "{\"status\":\"success\",\"data\":{\"sum\":\"...\"}, \"error\"\
            :\"\"}"
      x-swagger-router-controller: "Default"
  /profile:
    get:
      summary: "Get user profile"
      operationId: "profileGET"
      parameters:
      - name: "Authorization"
        in: "header"
        required: true
        type: "string"
      responses:
        "200":
          description: "{\"status\":\"success\",\"data\":{\"organizationPlan\":\"\
            cruising_speed\",\"organizationName\":\"Digital Cortex\",\"lastName\"\
            :\"Cortex\",\"status\":\"active\",\"email\":\"digitalcortex@gmail.com\"\
            ,\"role\":\"Super Admin\",\"firstName\":\"Digital\",\"id\":1},\"error\"\
            :\"\"}"
      x-swagger-router-controller: "Default"
  /updateprofile:
    post:
      summary: "Update user profile"
      operationId: "updateprofilePOST"
      parameters:
      - in: "body"
        name: "body"
        description: "Request payload in application/json"
        required: true
        schema:
          $ref: "#/definitions/update-profile"
      - name: "Authorization"
        in: "header"
        required: true
        type: "string"
      responses:
        "200":
          description: "{\"status\":\"success\",\"data\":{\"isUpdateSuccess\":\"true\"\
            },\"error\":\"\"}"
      x-swagger-router-controller: "Default"
  /allroles:
    get:
      summary: "Get all roles"
      operationId: "allrolesGET"
      parameters:
      - name: "Authorization"
        in: "header"
        required: true
        type: "string"
      responses:
        "200":
          description: "{\"status\":\"success\",\"data\":{\"plan\":[{\"id\":2,\"name\"\
            :\"admin\"},{\"id\":3,\"name\":\"editor\"},{\"id\":4,\"name\":\"viewer\"\
            }]}"
      x-swagger-router-controller: "Default"
  /changepassword:
    post:
      summary: "Change user password"
      operationId: "changepasswordPOST"
      parameters:
      - in: "body"
        name: "body"
        description: "Request payload in application/json"
        required: true
        schema:
          $ref: "#/definitions/changepassword-form"
      - name: "Authorization"
        in: "header"
        required: true
        type: "string"
      responses:
        "200":
          description: "{\"status\":\"success\",\"data\":{\"isPasswordUpdated\":\"\
            true\"},\"error\":\"\"}"
      x-swagger-router-controller: "Default"
  /remove:
    get:
      summary: "Inactivate single as well as multiple user"
      operationId: "removeGET"
      parameters:
      - name: "Authorization"
        in: "header"
        required: true
        type: "string"
      - name: "ids"
        in: "query"
        description: "users ids you want to remove"
        required: true
        type: "string"
      responses:
        "200":
          description: "{\"status\":\"success\",\"data\":{\"isUsersRemoved\":true},\"\
            error\":\"\"}"
      x-swagger-router-controller: "Default"
  /activate:
    get:
      summary: "Activate single as well as multiple users"
      operationId: "activateGET"
      parameters:
      - name: "Authorization"
        in: "header"
        required: true
        type: "string"
      - name: "ids"
        in: "query"
        description: "users ids you want to activate"
        required: true
        type: "string"
      responses:
        "200":
          description: "{\"status\":\"success\",\"data\":{\"isUsersActivated\":true},\"\
            error\":\"\"}"
      x-swagger-router-controller: "Default"
  /signout:
    get:
      summary: "Sign out from the account"
      operationId: "signoutGET"
      parameters:
      - name: "Authorization"
        in: "header"
        required: true
        type: "string"
      responses:
        "200":
          description: "{\"status\":\"success\",\"data\":{\"isSignoutSuccess\":\"\
            true\"},\"error\":\"\"}"
      x-swagger-router-controller: "Default"
  /update:
    post:
      summary: "Update user role, name status and organization."
      operationId: "updatePOST"
      parameters:
      - name: "Authorization"
        in: "header"
        required: true
        type: "string"
      - in: "body"
        name: "body"
        description: "request payload in application/json"
        required: true
        schema:
          $ref: "#/definitions/update"
      responses:
        "200":
          description: "{\"status\":\"success\",\"data\":{\"isUserUpdated\":true},\"\
            error\":\"\"}"
      x-swagger-router-controller: "Default"
definitions:
  sign-up:
    type: "object"
    properties:
      firstName:
        type: "string"
      lastName:
        type: "string"
      email:
        type: "string"
      password:
        type: "string"
  login:
    type: "object"
    properties:
      email:
        type: "string"
      password:
        type: "string"
  add:
    type: "object"
    properties:
      num1:
        type: "number"
      num2:
        type: "number"
  update-profile:
    type: "object"
    properties:
      firstName:
        type: "string"
      lastName:
        type: "string"
  update:
    type: "object"
    properties:
      userId:
        type: "number"
      firstName:
        type: "string"
      lastName:
        type: "string"
      roleId:
        type: "number"
      status:
        type: "string"
      orgId:
        type: "number"
  changepassword-form:
    type: "object"
    properties:
      oldPassword:
        type: "string"
      newPassword:
        type: "string"
